feat: use secret store for PSK key (#33)
edgexfoundry/device-coap-c pull request #34
Opened 2022-02-02 14:50 UTC by iain-anderson

Signed-off-by: Iain Anderson <iain@iotechsys.com>

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-coap-c/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) - no unit tests for C device services
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?) - documentation updated in this PR
  <link to docs PR>

## Testing Instructions

Run the service in PSK mode with a simulated device (see "Testing/Simulation for CoAP Server" in the README
## New Dependency Instructions (If applicable)

2022-02-02 15:24 UTC, sudhamani-hcl commented
LGTM

2022-02-02 15:26 UTC, sudhamani-hcl submitted a review, later dismissed
LGTM

2022-02-02 16:53 UTC, lenny-intel requested changes

2022-02-02 16:53 UTC, lenny-intel commented on README.md
> +      path = "device-coap"
For consistency the path should be the name of the secret not the service name. Suggest using PSK. 
In secure mode the service should be part of the base path that this `path` is appended to it like:
```
.../device-coap/psk
```
`.../device-coap` is the secret store in Vault for Device Coap.
`.../device-coap/psk` is a Secret within the Device Coap secret store in vault.

The path in the InsucureSecrets needs to mimic that used for Vault.

2022-02-02 16:53 UTC, lenny-intel commented on src/c/device-coap.c
> +      iot_data_t *secrets = devsdk_get_secrets (driver->service, "device-coap");
```suggestion
      iot_data_t *secrets = devsdk_get_secrets (driver->service, "psk");
```

2022-02-02 16:53 UTC, lenny-intel commented on res/configuration.toml
> +  [Writable.InsecureSecrets]
Also need the `SecretStore` cinfig section which should be:

```
[SecretStore]
Type = "vault"
Protocol = "http"
Host = "localhost"
Port = 8200
Path = "device-coap/"
TokenFile = "/tmp/edgex/secrets/device-coap/secrets-token.json"
RootCaCertPath = ""
ServerName = ""
  [SecretStore.Authentication]
  AuthType = "X-Vault-Token"
```
Note this is where the `device-coap` is added to the path.

2022-02-03 10:43 UTC, iain-anderson commented
updated with changes recommended by @lenny-intel

2022-02-07 15:50 UTC, lenny-intel requested changes

2022-02-07 15:50 UTC, lenny-intel commented on res/configuration-native.toml
> +        PskKey = "ME42aURHZ3Uva0Y0eG9lZw=="
Missing name changes that were applied in the README

2022-02-07 15:50 UTC, lenny-intel commented on res/configuration.toml
> +      [Writable.InsecureSecrets.device-coap.Secrets]
Missing name changes that were applied in the README

2022-02-08 15:35 UTC, merged