refac: bump to v2.2
edgexfoundry/device-coap-c pull request #42
Opened 2022-08-02 14:49 UTC by iain-anderson

Signed-off-by: Iain Anderson <iain@iotechsys.com>

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-coap-c/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

## New Dependency Instructions (If applicable)

2022-08-03 09:47 UTC, iain-anderson commented
Also update to Alpine 3.16, which includes its own libcbor, so no need to build that anymore

2022-11-02 17:01 UTC, lenny-intel requested changes

2022-11-02 17:01 UTC, lenny-intel commented on CHANGELOG.md
> +- Bump to SDK v2.1 ([#30](https://github.com/edgexfoundry/device-coap-c/issues/30)) ([#12271f6](https://github.com/edgexfoundry/device-coap-c/commits/12271f6))
This should be under v2.1.0 section

2022-11-03 17:20 UTC, iain-anderson commented
Fixed changelog and added missing default config values

2022-11-07 15:17 UTC, lenny-intel approved these changes
LGTM

2022-11-07 15:19 UTC, merged